# Notebook Summary

- merged all the cv's for matches and picks 
- exported them e/a as a merged csv 
- merged/joined radiant win to picks dataframe and exported as csv
- found that picks had a couple nulls (2 occurences, both were in 22 pick and team columns)
    - dunno wtf that means, maybe team rage quited? dunno i think these matches include qualifiers (inspect closer later if time)
    - match records have a few nulls, but only in for radiant/dire team id's
    - not too surprising, probly just no-name team or glitch when team changed name
    - can keep said rows if needs, just fill with zeros 
- matches df had more rows than picks, i'm guessing those can be explained with re-makes or something 
    - number is low so am not too concerned
    
- both picks data frames cleaned, no nulls, and updated columns with correct data types 
    - see picks dataframe dictionary
- matches still has the nulls, didn't correcting data types as i don't think it really matters for my analysis

In [201]:
import sys
sys.path.append('../')
import glob2 as glob
import json
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder

pd.options.display.max_columns = 100

%matplotlib inline

from sklearn import preprocessing
import warnings; warnings.simplefilter('ignore')

In [29]:
csv_file_list1 = ['picks1.csv', 'picks2.csv', 'picks3.csv', 'picks4.csv', 'picks5.csv']
csv_file_list2 = ['matches1.csv', 'matches2.csv','matches3.csv', 'matches4.csv', 'matches5.csv']

In [ ]:


pd.concat([pd.DataFrame([i], columns=['A']) for i in range(5)], 
          ignore_index=True)

NOTE: Files were renamed for convenience as the following: 
1. Starladder 
2. Epicenter
3. TI9 
4. Summit 11 
5. Chengdu

In [ ]:
csv_file_list1 = ['picks1.csv', 'picks2.csv', 'picks3.csv', 'picks4.csv', 'picks5.csv']
csv_file_list2 = ['matches1.csv', 'matches2.csv','matches3.csv', 'matches4.csv', 'matches5.csv']
list_of_dataframes = []
for filename in csv_file_list1:
    list_of_dataframes.append(pd.read_csv(filename))

picks_merged = pd.concat(list_of_dataframes)

#print(merged_df1)
#print(merged_df2)
#OUTPUT

In [30]:
# source: https://kite.com/python/answers/how-to-make-a-single-pandas-dataframe-from-multiple-%60.csv%60-files-in-python
csv_file_list1 = ['picks1.csv', 'picks2.csv', 'picks3.csv', 'picks4.csv', 'picks5.csv']
csv_file_list2 = ['matches1.csv', 'matches2.csv','matches3.csv', 'matches4.csv', 'matches5.csv']
list_of_dataframes = []
for filename in csv_file_list2:
    list_of_dataframes.append(pd.read_csv(filename))

merged_df2 = pd.concat(list_of_dataframes)

#print(merged_df1)
#print(merged_df2)
#OUTPUT

In [228]:
mpicks_df = picks_merged
mmatches_df = merged_df2
print(mpicks_df.shape)
print(mmatches_df.shape)
mpicks_df.isna().sum()

(1535, 67)
(1540, 11)

match_id     0
1is_pick     0
1team        0
1hero_id     0
2is_pick     0
2team        0
2hero_id     0
3is_pick     0
3team        0
3hero_id     0
4is_pick     0
4team        0
4hero_id     0
5is_pick     0
5team        0
5hero_id     0
6is_pick     0
6team        0
6hero_id     0
7is_pick     0
7team        0
7hero_id     0
8is_pick     0
8team        0
8hero_id     0
9is_pick     0
9team        0
9hero_id     0
10is_pick    0
10team       0
10hero_id    0
11is_pick    0
11team       0
11hero_id    0
12is_pick    0
12team       0
12hero_id    0
13is_pick    0
13team       0
13hero_id    0
14is_pick    0
14team       0
14hero_id    0
15is_pick    0
15team       0
15hero_id    0
16is_pick    0
16team       0
16hero_id    0
17is_pick    0
17team       0
17hero_id    0
18is_pick    0
18team       0
18hero_id    0
19is_pick    0
19team       0
19hero_id    0
20is_pick    0
20team       0
20hero_id    0
21is_pick    0
21team       0
21hero_id    0
22is_pick    0
22team       0
22hero_id    0
dtype: int64

In [224]:
picks_df = picks_merged
picks_df.shape
picks_df.isna().sum()

match_id     0
1is_pick     0
1team        0
1hero_id     0
2is_pick     0
2team        0
2hero_id     0
3is_pick     0
3team        0
3hero_id     0
4is_pick     0
4team        0
4hero_id     0
5is_pick     0
5team        0
5hero_id     0
6is_pick     0
6team        0
6hero_id     0
7is_pick     0
7team        0
7hero_id     0
8is_pick     0
8team        0
8hero_id     0
9is_pick     0
9team        0
9hero_id     0
10is_pick    0
10team       0
10hero_id    0
11is_pick    0
11team       0
11hero_id    0
12is_pick    0
12team       0
12hero_id    0
13is_pick    0
13team       0
13hero_id    0
14is_pick    0
14team       0
14hero_id    0
15is_pick    0
15team       0
15hero_id    0
16is_pick    0
16team       0
16hero_id    0
17is_pick    0
17team       0
17hero_id    0
18is_pick    0
18team       0
18hero_id    0
19is_pick    0
19team       0
19hero_id    0
20is_pick    0
20team       0
20hero_id    0
21is_pick    0
21team       0
21hero_id    0
22is_pick    0
22team       0
22hero_id    0
dtype: int64

In [50]:
picks_df.shape

(1537, 67)

In [47]:
matches_df = merged_df2
matches_df.shape

(1540, 11)

In [49]:
matches_df.isnull().sum()

Unnamed: 0          0
match_id            0
duration            0
leagueid            0
match_seq_num       0
series_id           0
series_type         0
patch               0
dire_team_id       29
radiant_team_id    33
radiant_win         0
dtype: int64

hmmm looks like i have 2 null in picks df and 62 in matches. Also, picks has 3 less rows than match history df

On inspection from cleaning notebooks, starladder and ti9 are the the main culpirits
 - 1 row off in ti9, 
 - 2 rows off in starladder

In [55]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1540 entries, 0 to 439
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1540 non-null   int64
 1   match_id         1540 non-null   int64
 2   duration         1540 non-null   int64
 3   leagueid         1540 non-null   int64
 4   match_seq_num    1540 non-null   int64
 5   series_id        1540 non-null   int64
 6   series_type      1540 non-null   int64
 7   patch            1540 non-null   int64
 8   dire_team_id     1511 non-null   float64
 9   radiant_team_id  1507 non-null   float64
 10  radiant_win      1540 non-null   bool
dtypes: bool(1), float64(2), int64(8)
memory usage: 133.8 KB

In [56]:
picks_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1537 entries, 0 to 439
Data columns (total 67 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   match_id   1537 non-null   int64
 1   1is_pick   1537 non-null   int64
 2   1team      1537 non-null   int64
 3   1hero_id   1537 non-null   int64
 4   2is_pick   1537 non-null   int64
 5   2team      1537 non-null   int64
 6   2hero_id   1537 non-null   int64
 7   3is_pick   1537 non-null   int64
 8   3team      1537 non-null   int64
 9   3hero_id   1537 non-null   int64
 10  4is_pick   1537 non-null   int64
 11  4team      1537 non-null   int64
 12  4hero_id   1537 non-null   int64
 13  5is_pick   1537 non-null   int64
 14  5team      1537 non-null   int64
 15  5hero_id   1537 non-null   int64
 16  6is_pick   1537 non-null   int64
 17  6team      1537 non-null   int64
 18  6hero_id   1537 non-null   int64
 19  7is_pick   1537 non-null   int64
 20  7team      1537 non-null   int64
 21  7hero_id   1537 non-null   int64
 22  8is_pick   1537 non-null   int64
 23  8team      1537 non-null   int64
 24  8hero_id   1537 non-null   int64
 25  9is_pick   1537 non-null   int64
 26  9team      1537 non-null   int64
 27  9hero_id   1537 non-null   int64
 28  10is_pick  1537 non-null   int64
 29  10team     1537 non-null   int64
 30  10hero_id  1537 non-null   int64
 31  11is_pick  1537 non-null   int64
 32  11team     1537 non-null   int64
 33  11hero_id  1537 non-null   int64
 34  12is_pick  1537 non-null   int64
 35  12team     1537 non-null   int64
 36  12hero_id  1537 non-null   int64
 37  13is_pick  1537 non-null   int64
 38  13team     1537 non-null   int64
 39  13hero_id  1537 non-null   int64
 40  14is_pick  1537 non-null   int64
 41  14team     1537 non-null   int64
 42  14hero_id  1537 non-null   int64
 43  15is_pick  1537 non-null   int64
 44  15team     1537 non-null   int64
 45  15hero_id  1537 non-null   int64
 46  16is_pick  1537 non-null   int64
 47  16team     1537 non-null   int64
 48  16hero_id  1537 non-null   int64
 49  17is_pick  1537 non-null   int64
 50  17team     1537 non-null   int64
 51  17hero_id  1537 non-null   int64
 52  18is_pick  1537 non-null   int64
 53  18team     1537 non-null   int64
 54  18hero_id  1537 non-null   int64
 55  19is_pick  1537 non-null   int64
 56  19team     1537 non-null   int64
 57  19hero_id  1537 non-null   int64
 58  20is_pick  1537 non-null   int64
 59  20team     1537 non-null   int64
 60  20hero_id  1537 non-null   int64
 61  21is_pick  1537 non-null   int64
 62  21team     1537 non-null   int64
 63  21hero_id  1537 non-null   int64
 64  22is_pick  1537 non-null   int64
 65  22team     1535 non-null   float64
 66  22hero_id  1535 non-null   float64
dtypes: float64(2), int64(65)
memory usage: 816.5 KB

In [196]:
picks_df

,match_id,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
0,4770332364,True,True,33,True,False,55,True,True,94,True,False,102,True,True,53,True,False,88,True,True,69,True,False,6,True,False,3,True,True,87,True,True,36,True,False,77,True,True,65,True,False,18,True,False,16,True,True,52,True,False,25,True,True,46,True,False,29,True,True,50,True,True,7,True,False,17
1,4770343012,True,True,53,True,False,88,True,True,16,True,False,111,True,True,69,True,False,55,True,True,102,True,False,6,True,False,100,True,True,65,True,True,29,True,False,89,True,True,13,True,False,46,True,False,86,True,True,7,True,False,57,True,True,10,True,False,39,True,True,76,True,True,106,True,False,36
2,4770458746,True,True,6,True,False,55,True,True,53,True,False,88,True,True,52,True,False,102,True,True,69,True,False,111,True,False,95,True,True,15,True,True,65,True,False,18,True,True,33,True,False,112,True,False,16,True,True,86,True,False,25,True,True,87,True,False,94,True,True,49,True,True,39,True,False,10
3,4770490885,True,True,6,True,False,88,True,True,53,True,False,102,True,True,15,True,False,111,True,True,55,True,False,69,True,False,16,True,True,107,True,True,18,True,False,54,True,True,8,True,False,89,True,False,87,True,True,95,True,False,42,True,True,64,True,False,46,True,True,35,True,True,94,True,False,65
4,4770544546,True,True,94,True,False,88,True,True,69,True,False,55,True,True,53,True,False,25,True,True,102,True,False,111,True,False,19,True,True,95,True,True,76,True,False,27,True,True,15,True,False,45,True,False,52,True,True,16,True,False,17,True,True,39,True,False,29,True,True,6,True,True,60,True,False,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,5125693570,True,False,25,True,True,66,True,False,72,True,True,60,True,False,23,True,True,89,True,False,9,True,True,102,True,True,87,True,False,76,True,False,6,True,True,41,True,False,88,True,True,54,True,True,16,True,False,90,True,True,17,True,False,57,True,True,81,True,False,114,True,False,99,True,True,10
436,5125919642,True,False,25,True,True,66,True,False,41,True,True,89,True,False,72,True,True,60,True,False,9,True,True,57,True,True,86,True,False,76,True,False,35,True,True,102,True,False,52,True,True,6,True,True,90,True,False,85,True,True,46,True,False,104,True,True,10,True,False,54,True,False,81,True,True,8
437,5125994965,True,True,25,True,False,66,True,True,72,True,False,60,True,True,41,True,False,9,True,True,7,True,False,97,True,False,44,True,True,10,True,True,13,True,False,31,True,True,23,True,False,57,True,False,53,True,True,30,True,False,121,True,True,98,True,False,106,True,True,76,True,True,47,True,False,19
438,5126075663,True,True,89,True,False,25,True,True,76,True,False,9,True,True,7,True,False,41,True,True,60,True,False,66,True,False,73,True,True,98,True,True,79,True,False,68,True,True,57,True,False,93,True,False,52,True,True,90,True,False,104,True,True,23,True,False,27,True,True,59,True,True,120,True,False,70
439,5126164317,True,True,25,True,False,9,True,True,41,True,False,60,True,True,98,True,False,66,True,True,87,True,False,57,True,False,52,True,True,89,True,True,73,True,False,76,True,True,72,True,False,85,True,False,26,True,True,7,True,False,13,True,True,10,True,False,23,True,True,47,True,True,99,True,False,46

In [ ]:
picks_df

In [ ]:
# using dictionary to convert specific columns 
convert_dict = {'A': int, 
                'C': float
               } 
  
df = df.astype(convert_dict) 
print(df.dtypes)

In [82]:
picks_df.dropna(axis=0, inplace=True)

In [83]:
picks_df.isna()

,match_id,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
436,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
437,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1]:
#picks_df.astype({'22team': 'int64', '22hero_id': 'in64'}).dtypes

In [84]:
# picks dictionary
picks_dict = {'match_id': int, '1is_pick': bool, '1team': bool, '1hero_id': int,
               '2is_pick': bool, '2team': bool, '2hero_id': int, 
               '3is_pick': bool, '3team': bool, '3hero_id': int, 
               '4is_pick': bool, '4team': bool, '4hero_id': int, 
               '5is_pick': bool, '5team': bool, '5hero_id': int, 
               '6is_pick': bool, '6team': bool, '6hero_id': int, 
               '7is_pick': bool, '7team': bool, '7hero_id': int, 
               '8is_pick': bool, '8team': bool, '8hero_id': int, 
               '9is_pick': bool, '9team': bool, '9hero_id': int, 
               '10is_pick': bool, '10team':bool, '10hero_id': int, 
               '11is_pick': bool, '11team':bool, '11hero_id': int, 
               '12is_pick': bool, '12team':bool, '12hero_id': int,
               '13is_pick': bool, '13team':bool, '13hero_id': int, 
               '14is_pick': bool, '14team':bool, '14hero_id': int, 
               '15is_pick': bool, '15team':bool, '15hero_id': int, 
               '16is_pick': bool, '16team':bool, '16hero_id': int, 
               '17is_pick': bool, '17team':bool, '17hero_id': int,
               '18is_pick': bool, '18team':bool, '18hero_id': int, 
               '19is_pick': bool, '19team':bool, '19hero_id': int,
               '20is_pick': bool, '20team':bool, '20hero_id': int,
               '21is_pick': bool, '21team':bool, '21hero_id': int, 
                '22is_pick': bool, '22team':bool, '22hero_id': int}

picks_df = picks_df.astype(picks_dict)

In [91]:
picks_df.shape

(1535, 67)

In [89]:
picks_df.to_csv('data/picks_merged_clean.csv')

In [92]:
matches_df.shape

(1540, 11)

In [95]:
check = picks_df['match_id']

In [117]:
f = picks_df['match_id'].isin(matches_df['match_id'])

In [118]:
print(f)

0      True
1      True
2      True
3      True
4      True
       ...
435    True
436    True
437    True
438    True
439    True
Name: match_id, Length: 1535, dtype: bool

In [94]:
matches_df.isna().sum()

Unnamed: 0          0
match_id            0
duration            0
leagueid            0
match_seq_num       0
series_id           0
series_type         0
patch               0
dire_team_id       29
radiant_team_id    33
radiant_win         0
dtype: int64

Merging the extracted drafting features with the rest of the match data.

In [218]:
a = matches_df[['match_id']]
b = picks_df[['match_id']]

In [175]:
p = picks_df[['match_id']] 
m = matches_df.copy()

common = p.merge(matches_df,on=['match_id'])
common.shape

(1535, 11)

In [178]:
## !!!!!
matches_cleaned = common
matches_cleaned.to_csv('matches_cleaned.csv')

In [193]:
df = matches_cleaned
grouped_df = df.groupby("patch")

In [180]:
matches_cleaned.isna().sum()

match_id            0
Unnamed: 0          0
duration            0
leagueid            0
match_seq_num       0
series_id           0
series_type         0
patch               0
dire_team_id       29
radiant_team_id    33
radiant_win         0
dtype: int64

In [144]:
picks = picks_df.copy()
matches = matches_df[['match_id', 'radiant_win']]

In [151]:
picks2 = matches.merge(picks, on=['match_id'], how='left')
picks2.isna().sum()
picks2.dropna(axis=0, inplace=True )

In [158]:
picks2

,match_id,radiant_win,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
0,4833593109,True,True,False,38.0,True,True,111.0,True,False,55.0,True,True,107.0,True,False,46.0,True,True,66.0,True,False,18.0,True,True,16.0,True,True,37.0,True,False,65.0,True,False,57.0,True,True,88.0,True,False,39.0,True,True,121.0,True,True,67.0,True,False,68.0,True,True,7.0,True,False,80.0,True,True,51.0,True,False,43.0,True,False,100.0,True,True,106.0
1,4774328947,False,True,True,111.0,True,False,46.0,True,True,16.0,True,False,6.0,True,True,18.0,True,False,55.0,True,True,69.0,True,False,88.0,True,False,121.0,True,True,87.0,True,True,42.0,True,False,89.0,True,True,38.0,True,False,8.0,True,False,78.0,True,True,95.0,True,False,15.0,True,True,39.0,True,False,96.0,True,True,54.0,True,True,65.0,True,False,17.0
2,4779407768,True,True,True,10.0,True,False,55.0,True,True,33.0,True,False,69.0,True,True,15.0,True,False,65.0,True,True,16.0,True,False,111.0,True,False,95.0,True,True,112.0,True,True,88.0,True,False,78.0,True,True,36.0,True,False,8.0,True,False,19.0,True,True,96.0,True,False,119.0,True,True,54.0,True,False,23.0,True,True,46.0,True,True,100.0,True,False,17.0
3,4833371463,True,True,False,111.0,True,True,38.0,True,False,37.0,True,True,55.0,True,False,88.0,True,True,66.0,True,False,16.0,True,True,102.0,True,True,10.0,True,False,46.0,True,False,65.0,True,True,68.0,True,False,107.0,True,True,18.0,True,True,119.0,True,False,5.0,True,True,23.0,True,False,7.0,True,True,8.0,True,False,129.0,True,False,67.0,True,True,2.0
4,4833120790,False,True,False,37.0,True,True,38.0,True,False,111.0,True,True,55.0,True,False,88.0,True,True,66.0,True,False,16.0,True,True,18.0,True,True,121.0,True,False,46.0,True,False,65.0,True,True,114.0,True,False,57.0,True,True,95.0,True,True,107.0,True,False,86.0,True,True,17.0,True,False,42.0,True,True,90.0,True,False,29.0,True,False,68.0,True,True,129.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535,5114927085,True,True,False,85.0,True,True,7.0,True,False,90.0,True,True,72.0,True,False,9.0,True,True,97.0,True,False,66.0,True,True,81.0,True,True,25.0,True,False,107.0,True,False,5.0,True,True,98.0,True,False,23.0,True,True,65.0,True,True,121.0,True,False,64.0,True,True,96.0,True,False,11.0,True,True,54.0,True,False,39.0,True,False,41.0,True,True,43.0
1536,5114498359,True,True,False,59.0,True,True,66.0,True,False,34.0,True,True,7.0,True,False,57.0,True,True,76.0,True,False,97.0,True,True,90.0,True,True,8.0,True,False,44.0,True,False,47.0,True,True,99.0,True,False,98.0,True,True,33.0,True,True,25.0,True,False,53.0,True,True,29.0,True,False,23.0,True,True,46.0,True,False,93.0,True,False,40.0,True,True,72.0
1537,5056346258,False,True,True,97.0,True,False,72.0,True,True,84.0,True,False,66.0,True,True,79.0,True,False,60.0,True,True,23.0,True,False,85.0,True,False,25.0,True,True,9.0,True,True,86.0,True,False,16.0,True,True,76.0,True,False,54.0,True,False,96.0,True,True,31.0,True,False,106.0,True,True,8.0,True,False,57.0,True,True,98.0,True,True,104.0,True,False,41.0
1538,5060704777,True,True,False,102.0,True,True,86.0,True,False,100.0,True,True,25.0,True,False,97.0,True,True,41.0,True,False,66.0,True,True,90.0,True,True,57.0,True,False,23.0,True,False,114.0,True,True,101.0,True,False,46.0,True,True,10.0,True,True,111.0,True,False,79.0,True,True,72.0,True,False,76.0,True,True,38.0,True,False,17.0,True,False,4.0,True,True,61.0
1539,5055077558,True,True,False,19.0,True,True,60.0,True,False,3.0,True,True,72.0,True,False,79.0,True,True,84.0,True,False,90.0,True,True,23.0,True,True,25.0,True,False,102.0,True,False,93.0,True,True,7.0,True,False,82.0,True,True,10.0,True,True,121.0,True,False,81.0,True,True,18.0,True,False,46.0,True,True,95.0,True,False,47.0,True,False,99.0,True,True,76.0

In [159]:
# picks dictionary
picks_dict = {'match_id': int, '1is_pick': bool, '1team': bool, '1hero_id': int,
               '2is_pick': bool, '2team': bool, '2hero_id': int, 
               '3is_pick': bool, '3team': bool, '3hero_id': int, 
               '4is_pick': bool, '4team': bool, '4hero_id': int, 
               '5is_pick': bool, '5team': bool, '5hero_id': int, 
               '6is_pick': bool, '6team': bool, '6hero_id': int, 
               '7is_pick': bool, '7team': bool, '7hero_id': int, 
               '8is_pick': bool, '8team': bool, '8hero_id': int, 
               '9is_pick': bool, '9team': bool, '9hero_id': int, 
               '10is_pick': bool, '10team':bool, '10hero_id': int, 
               '11is_pick': bool, '11team':bool, '11hero_id': int, 
               '12is_pick': bool, '12team':bool, '12hero_id': int,
               '13is_pick': bool, '13team':bool, '13hero_id': int, 
               '14is_pick': bool, '14team':bool, '14hero_id': int, 
               '15is_pick': bool, '15team':bool, '15hero_id': int, 
               '16is_pick': bool, '16team':bool, '16hero_id': int, 
               '17is_pick': bool, '17team':bool, '17hero_id': int,
               '18is_pick': bool, '18team':bool, '18hero_id': int, 
               '19is_pick': bool, '19team':bool, '19hero_id': int,
               '20is_pick': bool, '20team':bool, '20hero_id': int,
               '21is_pick': bool, '21team':bool, '21hero_id': int, 
                '22is_pick': bool, '22team':bool, '22hero_id': int}

picks_cleaned = picks2.astype(picks_dict)

In [258]:
picks_cleaned.shape

(1535, 68)

In [179]:
### !!!!!!!!!!!!!!!!!!
picks_cleaned.to_csv('picks_merged_cleaned_wRWINS.csv')

In [165]:
matches_df.isna().sum()

Unnamed: 0          0
match_id            0
duration            0
leagueid            0
match_seq_num       0
series_id           0
series_type         0
patch               0
dire_team_id       29
radiant_team_id    33
radiant_win         0
dtype: int64

In [167]:
matches_df.shape

(1540, 11)

In [172]:
print(picks_df.shape)
print(picks_cleaned.shape)

(1535, 67)
(1535, 68)

In [260]:
groupedDF = matches_df.filter(items=['match_id','radiant_win',
                                          'patch'])  # Remove columns
groupedDF = groupedDF.groupby(['patch']).count()  # Perform Aggregate
print(groupedDF)

       match_id  radiant_win
patch
40          374          374
41         1166         1166

In [240]:
matches = matches_df[matches_df.patch == 41]
matches.shape
matches.info

<bound method DataFrame.info of      Unnamed: 0    match_id  duration  leagueid  match_seq_num  series_id  \
0             0  4833593109      4036     10979     4062972494     337111
3             3  4833371463      2976     10979     4062797533     337111
4             4  4833120790      2700     10979     4062637540     337111
5             5  4835973421      3504     10979     4064617551     337330
6             6  4835092211      2530     10979     4063983045     337299
..          ...         ...       ...       ...            ...        ...
435         435  5114927085       887     11280     4291834666     386573
436         436  5114498359      1365     11280     4291475848     386464
437         437  5056346258       988     11280     4241637919     374084
438         438  5060704777      1137     11280     4245399407     375084
439         439  5055077558      1223     11280     4240590934     373748

     series_type  patch  dire_team_id  radiant_team_id  radiant_win
0              1     41     7118032.0         111474.0         True
3              1     41      111474.0        7118032.0         True
4              1     41      111474.0        7118032.0        False
5              1     41     6214973.0        7059982.0        False
6              1     41     7137328.0        7118032.0         True
..           ...    ...           ...              ...          ...
435            1     41     7409177.0        6209143.0         True
436            1     41     7121518.0        2108395.0         True
437            1     41     6214973.0        7424508.0        False
438            1     41     7441136.0             67.0         True
439            1     41     7404529.0        2108395.0         True

[1166 rows x 11 columns]>

In [ ]:
matches = matches.drop(columns='Unnamed: 0')

In [257]:
matches.shape

(1166, 10)

In [248]:
# picks_cleaned = matches2.merge(cpicks, on=['match_id'])
DPC_cleaned = matches.merge(picks_cleaned, on=['match_id'])
DPC_cleaned.head()

,match_id,duration,leagueid,match_seq_num,series_id,series_type,patch,dire_team_id,radiant_team_id,radiant_win_x,radiant_win_y,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
0,4833593109,4036,10979,4062972494,337111,1,41,7118032.0,111474.0,True,True,True,False,38,True,True,111,True,False,55,True,True,107,True,False,46,True,True,66,True,False,18,True,True,16,True,True,37,True,False,65,True,False,57,True,True,88,True,False,39,True,True,121,True,True,67,True,False,68,True,True,7,True,False,80,True,True,51,True,False,43,True,False,100,True,True,106
1,4833371463,2976,10979,4062797533,337111,1,41,111474.0,7118032.0,True,True,True,False,111,True,True,38,True,False,37,True,True,55,True,False,88,True,True,66,True,False,16,True,True,102,True,True,10,True,False,46,True,False,65,True,True,68,True,False,107,True,True,18,True,True,119,True,False,5,True,True,23,True,False,7,True,True,8,True,False,129,True,False,67,True,True,2
2,4833120790,2700,10979,4062637540,337111,1,41,111474.0,7118032.0,False,False,True,False,37,True,True,38,True,False,111,True,True,55,True,False,88,True,True,66,True,False,16,True,True,18,True,True,121,True,False,46,True,False,65,True,True,114,True,False,57,True,True,95,True,True,107,True,False,86,True,True,17,True,False,42,True,True,90,True,False,29,True,False,68,True,True,129
3,4835973421,3504,10979,4064617551,337330,1,41,6214973.0,7059982.0,False,False,True,False,66,True,True,52,True,False,120,True,True,88,True,False,55,True,True,37,True,False,16,True,True,102,True,True,86,True,False,53,True,False,18,True,True,89,True,False,106,True,True,47,True,True,99,True,False,68,True,True,77,True,False,42,True,True,17,True,False,113,True,False,76,True,True,65
4,4835092211,2530,10979,4063983045,337299,1,41,7137328.0,7118032.0,True,True,True,True,38,True,False,65,True,True,66,True,False,111,True,True,88,True,False,46,True,True,37,True,False,68,True,False,16,True,True,52,True,True,86,True,False,7,True,True,106,True,False,82,True,False,42,True,True,55,True,False,71,True,True,81,True,False,107,True,True,17,True,True,121,True,False,76

In [263]:
DPC_cleaned.shape

(1162, 77)

In [261]:
DPC_cleaned.to_csv('DPC_matches_cleaned.csv')

JK!!! not quite fully cleaned!

In [1]:
DPC_cleaned['radiant_win'].mean()

NameError: name 'DPC_cleaned' is not defined